name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # O la rama que desees usar para despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # O la versión de Node.js que prefieras

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Login to Firebase
      run: echo "${{ secrets.FIREBASE_TOKEN }}" | firebase login:ci --token

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
